---
- name: Change web server port
  hosts: backend_pool
  become: true

  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Update web server port configuration
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen'
        line: 'Listen 8080'
        state: present
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
